apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: gee-tiles
  name: gee-tiles
spec:
  progressDeadlineSeconds: 2147483647
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      name: gee-tiles
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: gee-tiles
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - apps
      containers:
      - args:
        - start
        env:
        - name: PORT
          value: "5700"
        - name: ENVIRONMENT
          value: staging
        - name: LOCAL_URL
          value: http://gee-tiles.default.svc.cluster.local:5700
        - name: CT_URL
          valueFrom:
            secretKeyRef:
              key: CT_URL
              name: mssecrets
        - name: CT_TOKEN
          valueFrom:
            secretKeyRef:
              key: CT_TOKEN
              name: mssecrets
        - name: CT_REGISTER_MODE
          valueFrom:
            secretKeyRef:
              key: CT_REGISTER_MODE
              name: mssecrets
        - name: API_VERSION
          valueFrom:
            secretKeyRef:
              key: API_VERSION
              name: mssecrets
        - name: GCLOUD_STORAGE
          valueFrom:
            secretKeyRef:
              key: GCLOUD_BACKUPS_CREDENTIALS
              name: mssecrets
        - name: EE_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: EE_PRIVATE_KEY
              name: mssecrets
        - name: EE_ACCOUNT
          valueFrom:
            secretKeyRef:
              key: EE_ACCOUNT
              name: mssecrets
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              key: GEE_TILES_REDIS_URI
              name: dbsecrets
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /opt/geetiles/storage.json
        image: vizzuality/gee-tiles
        imagePullPolicy: Always
        name: gee-tiles
        ports:
        - containerPort: 5700
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 512M
          requests:
            cpu: 250m
            memory: 256M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
