apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gee-tiles
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: gee-tiles
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
